#include <iostream>
#include <math.h>
/*
https://projecteuler.net/overview=012
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
------------------------------------
Üçgen sayı dizisi, doğal sayılar eklenerek üretilir.
Böylece 7. üçgen sayısı 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28 olacaktır. İlk on terim ise şöyle olacaktır:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
İlk yedi üçgen sayısının tam bölenlerini listeleyelim:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
Bu listeye göre 28 ilk 5'ten fazla tam bölene sahip sayıdır.
Öyleyse 500'den fazla tam bölene sahip ilk üçgen sayı hangisidir?
*/
using namespace std;

/*
Bölen, sayının karekökünü aştığında bölümleri durdurarak
bir miktar hızlanma sağlanır. Kareköke kadar her tam bölen için
karekökün üstünde ilgili bir bölen daha vardır. Bu yüzden değişken 2 arttırılır.
*/
int kac_boleni_var(unsigned long int sayi)
{
  int tane=0;
  for (int i=2;i<=sqrt(sayi)+1;i++)
  {
    if(sayi%i==0)
      tane+=2;
  }
  if (sqrt(sayi)*sqrt(sayi)==sayi)
    tane++;
  return tane+2; // kendisine ve 1 e tam bölündüğü için 2 artırıp döndürüyoruz...
}

int main()
{
  unsigned long int bolen_sayisi,s=1,sayi=1;
  do{
    s++;
    sayi+=s;
  }while(kac_boleni_var(sayi)<=500);
  cout << "500 tam bolenli sayi : " << sayi << endl;
}
